### ISSUE TITLE
Not supported on Linux

### ISSUE THREAD

**Issue by tyzbit** [ChrisDeFreitas/Electron-FolderView#2]
Previous versions of the application worked on Linux, but now I see only Windows is supported.  Part of the appeal of Electron is it's cross-platform.  It's not that much more effort to support Linux, and if you did you'd have +1 happy user.

**Comment by ChrisDeFreitas** [comment]
I wasn't aware of that Folderview worked on Linux.  I use it on Windows 
and gave up trying to keep it cross platform compatible. And I've made 
changes (not uploaded as yet) that move it more towards the Windows world.

However, I think cross-platform support for Folderview is a good idea 
for a lot of reasons.  I've been playing with LXQT recently so I'll load 
it up and see what I can do.  I'm currently expanding the search 
function so I'll have to finish that first.

What version of Linux are you using Folderview in?  And let me know if 
you have any ideas.

Chris.

**Comment by tyzbit** [comment]
I use Linux Mint.  I think the primary thing that keeps it cross-platform is using relative paths as often as possible, and then having case switches where it's absolutely necessary.

**Comment by ChrisDeFreitas** [comment]
I moved away from using posix paths internally.  Just before reading 
your message I cleaned up a mess of code caused by not using posix 
paths.  I am also going back to the standard that all folder paths must 
end with a trailing slash.  It became a big issue in the new folder 
search functionality I'm working on.

Ok, I'll load up Mint and update the code from there.  I am shopping 
about for a new Linux desktop.  I was using LXDE but its been replaced 
by LXQT, but I want to see what a more full featured desktop feels 
like.  Although, after poking about with KDE, I really like the 
simplicity and sparseness of LXDE/LXQT.

I'll email when the next update happens.  But it won't be for a week or 
more because I'm heading into a busy period and there are a few more 
changes to make with this new file search functionality ( +testing etc).

Chris.

**Comment by ChrisDeFreitas** [comment]
tyzbit, I apologize.  I have not had an opportunity to move the code more towards Linux.  I thought I would be moving more of my activities into the Linux world and taking this code base along.  That hasn't happened because of the realities of work and the technical environments I work in.  

I know its at least a year later, but, I'm happy to support you if you are still interested in doing that.

Chris.

**Comment by tyzbit** [comment]
That's no problem, I'll be here to assist in testing the software whenever you do want to work on making it cross-platform capable.
